const express = require('express');
const router = express.Router();
const authController = require('../../controller/auth/auth');
router.get('/login', authController.getLogin);
router.post('/login', authController.postLogin);
router.get('/signup', authController.getSignup);
router.post('/signup', authController.postSignup);
router.post('/logout', authController.postLogout);
router.get('/reset', authController.getPwdReset);
router.post('/reset', authController.postPwdReset);
router.get('/reset/:token', authController.getNewPassword);
router.post('/reset/newpassword', authController.postNewPassword);
module.exports = router;